### PR TITLE
Wallet Connection

### PR DESCRIPTION
**Pull request by akshatmittal61**
Changes made in this PR:

- [x] Merging of client and API
- [x] CORS issue resolving
- [x] Env configs
- [x] Code refactoring
- [x] Wallet Connection
- [x] Assets Minting
- [x] Disconnect Wallet
- [x] Wallet Balance (in ETH)

### CODE REVIEW

**Comment by akshatmittal61** [comment]
Since the entire file structure is changed and the env for the client has shifted from `vite` to `CRA`, the deployment shall be done on `railway` only. Also, that would need to be reconfigured.

**Comment by akshatmittal61** [comment]
image
image

**Comment by VarunProhit** [comment]
in upload file page remove connect wallet button.
disable upload with an error to connect wallet that redirect you to main page

**Comment by akshatmittal61** [comment]
I have done the requested changes, please check

**Comment by akshatmittal61** [comment]
I have done all the changes, please review

**Pull request merged**
